server:
  host: "0.0.0.0"
  port: 5555
  log_level: "DEV"
  allow_headers: "*"
  allow_methods: "*"
  allow_origins: "http://localhost:3000, http://localhost:3001"
  csrf_protection: true
  csrf_secure: false
  csrf_domain: "localhost"

database:
  host: "postgres"
  port: 5432
  dbname: "postgres"
  user: "postgres"
  password: "password"
  sslmode: "prefer"
  loglevel: "error"
  auto_migrate: false

mailer:
  host: "smtp.gmail.com"
  port: 587
  username: "example@example-gmail.com"
  app_password: "foo bar baz qux"
  tls: true

echo_jwt:
  signing_key: "authsecret"
  token_lookup: "cookie:jwt"
  signing_method: "HS256"
  exp_in_hours: 72

auth_jwt:
  signing_key: "confirmationsecret"
  signing_method: "HS256"
  exp_in_hours: 1
